 const refs={
    heder: document.querySelector('.main-container'),
    inputForm: document.querySelector('.input-text'),
    gallery: document.querySelector('.gallery-list'),
    form: document.querySelector('.form-search'),
    lensSearch: document.querySelector('.logo-search'),
    item: document.querySelector('.gallery-list__item'),
    article: document.querySelector('article'),
    closeBtn: document.querySelector('.close-button'),
    trailerLink: document.querySelector('.trailer-link'),
    addToWatchBtn: document.querySelector('.add-to-watched-btn'),
    addToQueueBtn: document.querySelector('.add-to-queue-btn'),
    btnHome: document.querySelector('.home-page'),
    container: document.querySelector('.js-team__modal'),
    headerContainer: document.querySelector('.header'),
    btnMyLibrary: document.querySelector('.library-page'),
    btnAction: document.querySelector('.btn-my-library'),
    btnWatched: document.querySelector('.watched'),
    btnQueue: document.querySelector('.queue'),
    list: document.querySelector('.list'),
    pagination: document.getElementById('pagination'),
    paginationContainer: document.querySelector('.pagination__container'),
    arrowLeft: document.querySelector('.arrow_left'),
    arrowRight: document.querySelector('.arrow_right'),
    current_btn: document.querySelector('.pagenumbers button.active'),
    target: document.getElementById('foo'),
    modal: document.querySelector('[data-modal-spinner]'),
    body: document.querySelector('body'),
    switchToggle: document.querySelector('#codepen'),
    upBtn: document.querySelector('[data-up-btn]'),
    galleryContainer: document.querySelector('.cards-container'),
    observer: document.querySelector('.observer'),
}

export default refs;