import './sass/main.scss';
import './js/modal';
import './js/pagination';
import './js/search';
import './js/apiService';
import './js/renderPopularMovies';
import './js/modalTeam';
import './js/myLibrary';
import './js/pagination';