import './sass/main.scss';
import './js/refs.js';
import './js/modal';
import './js/apiService';
import './js/renderPopularMovies';
import './js/search';
import './js/modalTeam';
import './js/myLibrary';
import './js/pagination';
import './js/theme';
import './js/up-btn';
import './js/spinner';
import './js/genresSearch';
// import './js/scrollPagination';
// import './js/pag';
// import './js/firebase.js';
